### PR TITLE
GOG and 2H weapon scabbard support

### LINKED ISSUE #17: Assumes SkyrimSE GameRelease
https://github.com/SteveTownsend/ImmersiveEquipmentMeshGen/blob/main/ImmersiveEquipmentMeshGen/MeshHandler.cs#LL362C98-L362C109

This line assumes that it's SkyrimSE.  This will cause issues with GOG users which have the ini in a different spot.

You should be able to do this:
```cs
var lookup = new IniPathLookup();
var path = lookup.Get(theGameRelease);
```
There should also be a static entry point, like so:
```cs
var path = Mutagen.Bethesda.Inis.Ini.GetTypicalPath(theGameRelease);
```
But this is currently hidden with a todo to do a design pass on the API to make sure it's proper.  I'll look into that

### PR DESCRIPTION
**Pull request by SlavicPotato**
Should resolve #17

### CODE REVIEW

**Comment by SteveTownsend** [comment]
I'm out of town, can this wait till the weekend?

**Comment by SlavicPotato** [comment]
Yeah of course, tyt!

**Comment by H-QueerCoded** [comment]
Any chance this will be released?

**Review by SteveTownsend — APPROVED** [review]
Very belated review, sorry for the delay

**Comment by SteveTownsend** [comment]
It's merged now

**Comment by SlavicPotato** [comment]
Nope, closed 😄

**Comment by SteveTownsend** [comment]
I'm confused now. Everything is OK with the PR, correct? I merged it into main branch.

**Comment by SteveTownsend** [comment]
sorry. Done right this time.

**Pull request merged**
