### PR TITLE
Ensure scabbard child nodes have unique names

### PR DESCRIPTION
**Pull request by SlavicPotato**
I've noticed some (custom) weapons have scabbards with child nodes named after the parent which can cause nifskope clobbering 'ScbLeft' during sanitization on save.

### CODE REVIEW

**Comment by SteveTownsend** [comment]
Is action needed for the patcher? Sounds like the meshes are not correct.
I think it's standard to use *Scb *for the scabbard name?

In any case, that's a good reason for us not to optimize/sort on save.

**Comment by SlavicPotato** [comment]
Yeah this is basically incorrect, nifskope fixes it on save and doesn't seem to ever rename 'Scb' nodes (probably recognizes that it shouldn't) but the children instead. This isn't the case for our 'ScbLeft' nodes though, these may get renamed so the action is indeed needed. Each node in the tree should have an unique name anyway. Just to be clear: this change only applies to ScbLeft nodes.

**Comment by SteveTownsend** [comment]
I'm so sorry, I did not realize this was a new PR with a fix, and not comments on the closed one. Should be able to build this tonight or tomorrow.

**Comment by SlavicPotato** [comment]
No worries!

**Review by SteveTownsend — APPROVED** [review]
Looks OK to me, I will merge and build this. Thanks for another fix.

**Pull request merged**
